### ISSUE TITLE
Can`t compile on win10 GCC 9.2.0 What I do wrong

### ISSUE THREAD

**Issue by necros2k7** [packjpg/packJPG#25]
Z:\pakjpg>mingw32-make
g++ -c -o bitops.o bitops.cpp -I. -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer -std=c++14
bitops.cpp:12:10: fatal error: experimental/filesystem: No such file or directory
   12 | #include <experimental/filesystem>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make: *** [Makefile:28: bitops.o] Error 1

**Comment by TarVanimelde** [comment]
I haven't checked it recently, but I assume that you can just change the line to 

```#include <filesystem>```

now. You'll probably also have to replace any instances of "std::experimental::filesystem" with "std::filesystem". Let me know if that's not the case.
